// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddTrustReducer from "../add_trust_reducer";
import ClaimGateReducer from "../claim_gate_reducer";
import ClaimWardenReducer from "../claim_warden_reducer";
import ConsumeGrantReducer from "../consume_grant_reducer";
import DecideGrantReducer from "../decide_grant_reducer";
import GateDenyReducer from "../gate_deny_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import LogEventReducer from "../log_event_reducer";
import MarkChangeReducer from "../mark_change_reducer";
import OpenIncidentReducer from "../open_incident_reducer";
import RecordChangeReducer from "../record_change_reducer";
import RecordFixResultReducer from "../record_fix_result_reducer";
import RecordResultReducer from "../record_result_reducer";
import RecordSkillUseReducer from "../record_skill_use_reducer";
import RegisterDeviceReducer from "../register_device_reducer";
import RequestGrantReducer from "../request_grant_reducer";
import RequestRollbackReducer from "../request_rollback_reducer";
import RevokeAllReducer from "../revoke_all_reducer";
import SubmitRequestReducer from "../submit_request_reducer";
import UpdateIncidentReducer from "../update_incident_reducer";
import UpdateRequestReducer from "../update_request_reducer";
import UpsertSkillReducer from "../upsert_skill_reducer";

export type AddTrustParams = __Infer<typeof AddTrustReducer>;
export type ClaimGateParams = __Infer<typeof ClaimGateReducer>;
export type ClaimWardenParams = __Infer<typeof ClaimWardenReducer>;
export type ConsumeGrantParams = __Infer<typeof ConsumeGrantReducer>;
export type DecideGrantParams = __Infer<typeof DecideGrantReducer>;
export type GateDenyParams = __Infer<typeof GateDenyReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type LogEventParams = __Infer<typeof LogEventReducer>;
export type MarkChangeParams = __Infer<typeof MarkChangeReducer>;
export type OpenIncidentParams = __Infer<typeof OpenIncidentReducer>;
export type RecordChangeParams = __Infer<typeof RecordChangeReducer>;
export type RecordFixResultParams = __Infer<typeof RecordFixResultReducer>;
export type RecordResultParams = __Infer<typeof RecordResultReducer>;
export type RecordSkillUseParams = __Infer<typeof RecordSkillUseReducer>;
export type RegisterDeviceParams = __Infer<typeof RegisterDeviceReducer>;
export type RequestGrantParams = __Infer<typeof RequestGrantReducer>;
export type RequestRollbackParams = __Infer<typeof RequestRollbackReducer>;
export type RevokeAllParams = __Infer<typeof RevokeAllReducer>;
export type SubmitRequestParams = __Infer<typeof SubmitRequestReducer>;
export type UpdateIncidentParams = __Infer<typeof UpdateIncidentReducer>;
export type UpdateRequestParams = __Infer<typeof UpdateRequestReducer>;
export type UpsertSkillParams = __Infer<typeof UpsertSkillReducer>;

