// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  requester: __t.string(),
  target: __t.string(),
  capability: __t.string(),
  reason: __t.string(),
  command: __t.string(),
  plan: __t.string(),
  status: __t.string(),
  singleUse: __t.bool().name("single_use"),
  ttlSeconds: __t.u32().name("ttl_seconds"),
  createdAtUs: __t.u64().name("created_at_us"),
  expiresAtUs: __t.u64().name("expires_at_us"),
  decidedBy: __t.string().name("decided_by"),
});
