// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  grantId: __t.u64().name("grant_id"),
  device: __t.string(),
  command: __t.string(),
  preState: __t.string().name("pre_state"),
  inverseCommand: __t.string().name("inverse_command"),
  status: __t.string(),
  tsUs: __t.u64().name("ts_us"),
});
