// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  requester: __t.string(),
  target: __t.string(),
  capability: __t.string(),
  reason: __t.string(),
  command: __t.string(),
  plan: __t.string(),
  ttlSeconds: __t.u32(),
  autoApprove: __t.bool(),
};
