// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runbookId: __t.string().primaryKey().name("runbook_id"),
  deviceType: __t.string().name("device_type"),
  successes: __t.u32(),
  failures: __t.u32(),
  level: __t.u8(),
  updatedAtUs: __t.u64().name("updated_at_us"),
});
