// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  slug: __t.string().primaryKey(),
  title: __t.string(),
  category: __t.string(),
  tags: __t.string(),
  summary: __t.string(),
  body: __t.string(),
  runbook: __t.string(),
  risk: __t.string(),
  source: __t.string(),
  uses: __t.u32(),
  updatedAtUs: __t.u64().name("updated_at_us"),
});
