// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccessGrant = __t.object("AccessGrant", {
  id: __t.u64(),
  requester: __t.string(),
  target: __t.string(),
  capability: __t.string(),
  reason: __t.string(),
  command: __t.string(),
  plan: __t.string(),
  status: __t.string(),
  singleUse: __t.bool(),
  ttlSeconds: __t.u32(),
  createdAtUs: __t.u64(),
  expiresAtUs: __t.u64(),
  decidedBy: __t.string(),
});
export type AccessGrant = __Infer<typeof AccessGrant>;

export const Change = __t.object("Change", {
  id: __t.u64(),
  grantId: __t.u64(),
  device: __t.string(),
  command: __t.string(),
  preState: __t.string(),
  inverseCommand: __t.string(),
  status: __t.string(),
  tsUs: __t.u64(),
});
export type Change = __Infer<typeof Change>;

export const Device = __t.object("Device", {
  id: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  capabilities: __t.array(__t.string()),
  status: __t.string(),
  lastHeartbeatUs: __t.u64(),
  identity: __t.identity(),
});
export type Device = __Infer<typeof Device>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  tsUs: __t.u64(),
  kind: __t.string(),
  device: __t.string(),
  grantId: __t.u64(),
  detail: __t.string(),
});
export type Event = __Infer<typeof Event>;

export const ExpireTick = __t.object("ExpireTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ExpireTick = __Infer<typeof ExpireTick>;

export const Gate = __t.object("Gate", {
  id: __t.u8(),
  identity: __t.identity(),
});
export type Gate = __Infer<typeof Gate>;

export const Incident = __t.object("Incident", {
  id: __t.u64(),
  device: __t.string(),
  alert: __t.string(),
  runbookId: __t.string(),
  status: __t.string(),
  attempts: __t.u32(),
  tsUs: __t.u64(),
});
export type Incident = __Infer<typeof Incident>;

export const ReapTick = __t.object("ReapTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ReapTick = __Infer<typeof ReapTick>;

export const RunResult = __t.object("RunResult", {
  grantId: __t.u64(),
  device: __t.string(),
  exitCode: __t.i32(),
  output: __t.string(),
  healthOk: __t.bool(),
  rolledBack: __t.bool(),
  tsUs: __t.u64(),
});
export type RunResult = __Infer<typeof RunResult>;

export const RunbookTrust = __t.object("RunbookTrust", {
  runbookId: __t.string(),
  deviceType: __t.string(),
  successes: __t.u32(),
  failures: __t.u32(),
  level: __t.u8(),
  updatedAtUs: __t.u64(),
});
export type RunbookTrust = __Infer<typeof RunbookTrust>;

export const Skill = __t.object("Skill", {
  slug: __t.string(),
  title: __t.string(),
  category: __t.string(),
  tags: __t.string(),
  summary: __t.string(),
  body: __t.string(),
  runbook: __t.string(),
  risk: __t.string(),
  source: __t.string(),
  uses: __t.u32(),
  updatedAtUs: __t.u64(),
});
export type Skill = __Infer<typeof Skill>;

export const Trust = __t.object("Trust", {
  id: __t.u64(),
  requester: __t.string(),
  target: __t.string(),
  capability: __t.string(),
});
export type Trust = __Infer<typeof Trust>;

export const UserRequest = __t.object("UserRequest", {
  id: __t.u64(),
  text: __t.string(),
  status: __t.string(),
  result: __t.string(),
  tsUs: __t.u64(),
});
export type UserRequest = __Infer<typeof UserRequest>;

export const Warden = __t.object("Warden", {
  id: __t.u8(),
  identity: __t.identity(),
});
export type Warden = __Infer<typeof Warden>;

